[build]
  base = "acaineiro-app"
  publish = "backend/public"
  functions = "netlify/functions"
  command = "npm ci --omit=dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/api/admin/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/.netlify/functions/api/admin"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/api/uploads/:splat"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/.netlify/functions/api/app/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/.netlify/functions/api/app"
  status = 200

[[redirects]]
  from = "/"
  to = "/admin"
  status = 301

[[redirects]]
  from = "/orders-count"
  to = "/.netlify/functions/api/orders-count"
  status = 200
