[[headers]]
  for = "/app/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
